- .github/dependabot.yml
- .github/workflows/checks.yml
- .gitignore
- core/data/test/dummy_test.dart
- core/database/test/dummy_test.dart
- core/datastore/test/dummy_test.dart
- core/designsystem/test/dummy_test.dart
- core/domain/test/dummy_test.dart
- core/model/test/dummy_test.dart
- core/network/test/dummy_test.dart
- core/testing/test/dummy_test.dart
- core/ui/test/dummy_test.dart
- melos.yaml
- close #1 🦕
Dependabot の構成ファイルを追加します.
特になし
- https://docs.github.com/ja/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
> :green_heart: Dependabot の構成ファイルを追加

- .github/workflows/dependabot-auto-merge.yml
- close #3 🦕
dabot の自動マージワークフローを追加します.
特になし
-
> :green_heart: Dependabot の自動マージワークフローを追加

- .fvm/fvm_config.json
- core/common/pubspec.yaml
- core/data/pubspec.yaml
- core/database/pubspec.yaml
- core/datastore/pubspec.yaml
- core/designsystem/pubspec.yaml
- core/domain/pubspec.yaml
- core/model/pubspec.yaml
- core/network/pubspec.yaml
- core/testing/pubspec.yaml
- core/ui/pubspec.yaml
- melos.yaml
flutterSdkVersion を 3.16.5 -> 3.16.7 にバージョンアップします.
特になし
-
> :up: flutterSdkVersion 3.16.5 -> 3.16.7

- melos.yaml
- pubspec.yaml
name を flutter_template -> asis に変更します.
特になし
-
> :recycle: name flutter_template -> asis

- core/common/lib/core_common.dart
- core/common/lib/extension.dart
- core/common/lib/src/extension/index.dart
- core/common/lib/src/extension/receiver.dart
- core/common/test/dummy_test.dart
- core/common/test/extension/receiver_test.dart
> :sparkles: 拡張関数を追加

- .github/workflows/dependabot-auto-merge.yml
Dependabot の自動マージジョブを変更します.
- https://github.com/marketplace/actions/github-action-merge-dependabot
> :green_heart: Dependabot の自動マージジョブを変更

- .github/workflows/checks.yml
> :green_heart: dorny/paths-filter を導入

- app/ios/Podfile.lock
- app/ios/Runner.xcodeproj/project.pbxproj
- app/ios/Runner.xcworkspace/contents.xcworkspacedata
> :wrench: iOS ビルド時の生成ファイルを追加

- app/lib/main.dart
- app/pubspec.lock
- app/pubspec.yaml
package_info_plus を導入します.
- https://pub.dev/packages/package_info_plus
> :wrench: package_info_plus を導入

- app/ios/Podfile.lock
- app/ios/Runner.xcodeproj/project.pbxproj
- #28 で不足していた iOS ビルド関連ファイルを追加します.
-
> :wrench: package_info_plus 導入時の iOS ビルド関連ファイルを追加

- melos.yaml
> :wrench: 明示的に IntelliJ 用の設定を追加

- app/lib/main.dart
- app/test/widget_test.dart
- feature/auth/lib/feature_auth.dart
- feature/home/lib/feature_home.dart
- feature/settings/lib/feature_settings.dart
> :recycle: コードフォーマット

- melos.yaml
melos exec 関連のリファクタリングを実施します.
- https://melos.invertase.dev/configuration/scripts#exec
> :wrench: exec 関連のリファクタリング

- .gitattributes
> :wrench: gitattributes を追加

- app/lib/app_build_config.dart
- app/lib/main.dart
- app/pubspec.lock
- app/pubspec.yaml
- core/data/pubspec.lock
- core/database/pubspec.lock
- core/datastore/pubspec.lock
- core/domain/pubspec.lock
- core/model/lib/build_config.dart
- core/model/lib/core_model.dart
- core/model/lib/src/build_config/build_config.dart
- core/model/lib/src/build_config/build_config.g.dart
- core/model/lib/src/build_config/index.dart
- core/model/lib/src/index.dart
- core/model/pubspec.lock
- core/model/pubspec.yaml
- core/network/pubspec.lock
- core/ui/pubspec.lock
- feature/auth/pubspec.lock
- feature/home/pubspec.lock
- feature/settings/pubspec.lock
- melos.yaml
- close #27 🦕
core / feature パッケージで利用できるよう BuildConfig の定義を追加します.
-
> :sparkles: BuildConfig の定義を追加

- scripts/bootstrap.sh
`make bs` した際に実行されるスクリプトで開発環境がセットアップできるようカイゼンします.
具体的には以下の処理を追加しています.
- fvm install の処理を追加
- melos bs の処理を追加
- mason get の処理を追加
- 他に実行すべき項目がないかご確認いただきたいです
- スクリプトの出力内容に問題がないかご確認いただきたいです
-
> :wrench: bootstrap で現在の開発環境を整えられるようカイゼン

- README.md
README を更新します.
特になし
- https://contrib.rocks
> :books: README を更新

- renovate.json5
> ci: Renovate のグループ設定を追加

- .firebaserc
- .github/workflows/firebase-hosting-merge.yml
- .github/workflows/firebase-hosting-pull-request.yml
- .gitignore
- .tool-versions
- firebase.json
- close #55 🦕
開発環境の Firebase Hosting の設定を追加します.
ステージング環境, 本番環境は別途対応します.
- PR 作成時にプレビューが動作すること
- https://firebase.google.com/docs/hosting/frameworks/flutter?hl=ja
> ci: 開発環境の Firebase Hosting の設定を追加

- tools/git/message
Git のコミットメッセージテンプレートを Conventional Commits に準拠した形式に変更します.
特になし
- https://www.conventionalcommits.org/ja/v1.0.0/
- https://github.com/pvdlg/conventional-changelog-metahub?tab=readme-ov-file#commit-types
- https://github.com/commitizen/conventional-commit-types
> chore: Git のコミットメッセージテンプレートを Conventional Commits に準拠した形式に変更

- .tool-versions
> build: mise dart 3.2.5

- app/android/build.gradle
- app/android/gradle.properties
- app/android/settings.gradle
> build: Gradle 関連ファイルのカイゼン

- .github/workflows/firebase-hosting-merge.yml
- .github/workflows/firebase-hosting-pull-request.yml
Firebase Hosting ワークフローの不要なビルドステップを削除します.
デプロイが成功すること
-
> ci: Firebase Hosting ワークフローの不要なビルドステップを削除

- .github/workflows/actions-lint.yml
GitHub Actions の Lint ワークフローを追加します.
- https://github.com/reviewdog/action-actionlint
> ci: GitHub Actions の Lint ワークフローを追加

- core/data/pubspec.lock
- core/datastore/pubspec.lock
- core/domain/pubspec.lock
- core/model/lib/src/quest/quest.dart
- core/model/lib/src/quest/quest.freezed.dart
- core/model/pubspec.lock
- core/model/pubspec.yaml
- core/network/pubspec.lock
- core/ui/pubspec.lock
- feature/auth/pubspec.lock
- feature/home/pubspec.lock
- feature/quest/pubspec.lock
- feature/settings/pubspec.lock
- melos.yaml
> feat(model): Quest を追加

- .github/workflows/checks.yml
Checks ワークフローにステータスチェック用のジョブを追加します.
-
> ci: Checks ワークフローにステータスチェック用のジョブを追加

- renovate.json5
> ci(renovate): commitMessagePrefix を削除

- tools/bricks/feature/hooks/pubspec.lock
brick の pubspec.lock の dart を 3.2.4 -> 3.2.6 に更新します.
-
> chore(brick): pubspec.lock dart 3.2.4 -> 3.2.6

- catalog/lib/pages/auth_page.dart
- catalog/lib/pages/home_page.dart
- catalog/lib/pages/quest_page.dart
- catalog/lib/pages/settings_page.dart
- catalog/lib/widgetbook.dart
- catalog/lib/widgetbook.directories.g.dart
- catalog/lib/widgets/primary_color_container.dart
- #124
- いただいたPRに対してTheme-addonを追加しました。
- 後々、themeは入れたくなると思ったので、先に入れました。
また、usecaseがlightThemeとなっていたので変更しました（意図があったらすみません）。
- DynamicColorの部分は無視して、引数はnullを渡しています。
-
> refactor: widgetbookのaddonにthemeを追加 

- app/pubspec.lock
- catalog/pubspec.lock
- feature/auth/pubspec.lock
- feature/auth/pubspec.yaml
- feature/home/pubspec.lock
- feature/home/pubspec.yaml
- feature/quest/pubspec.lock
- feature/quest/pubspec.yaml
- feature/settings/pubspec.lock
- feature/settings/pubspec.yaml
> chore(deps): hooks_riverpod への依存を追加

- feature/settings/lib/src/ui/settings/component/build_config_tile_content.dart
- feature/settings/lib/src/ui/settings/component/index.dart
- feature/settings/lib/src/ui/settings/settings_page.dart
BuildConfig の情報を設定ページに追加します.
-
| <img src="https://github.com/tatsutakein-jp/asis-app/assets/19267812/d0d64285-9c8c-4bfb-af67-23331df92ba2" width="300" /> | <img src="https://github.com/tatsutakein-jp/asis-app/assets/19267812/686faba2-7466-42f6-8f80-2e8b92d6e6a8" width="300" /> |
> feat(settings): BuildConfig の情報を設定ページに追加

- renovate.json5
> chore: Renovate 構成ファイルのカイゼン

- .github/workflows/checks.yml
依存関係を事前にキャッシュし analyze と test の job を切り分けます.
-
> ci: 依存関係を事前にキャッシュし analyze と test の job を切り分け

- catalog/lib/components/quest_list_tile.dart
- catalog/lib/widgetbook.directories.g.dart
- catalog/pubspec.lock
- catalog/pubspec.yaml
- core/model/lib/quest.dart
- core/model/lib/src/quest/index.dart
- core/ui/lib/quest_list_title.dart
- core/ui/lib/src/quest_list_tile.dart
- close #222 🦕
クエストの一覧タイルコンポーネントを追加します．
-
> [GH-222] クエストの一覧タイルコンポーネントを追加

- core/data/lib/core_data.dart
- core/data/lib/quest_repository.dart
- core/data/lib/src/quest_repository.dart
- core/data/lib/src/quest_repository.g.dart
- core/data/pubspec.lock
- core/data/pubspec.yaml
- core/database/lib/quest_dao.dart
- core/database/lib/src/quest/isar_quest_dao.dart
- core/database/lib/src/quest/quest_dao.dart
- close #226 🦕
クエストのリポジトリを追加します．
-
> [GH-226] クエストのリポジトリを追加

- app/ios/Podfile.lock
- app/lib/app_initializer.dart
- app/lib/main.dart
- app/pubspec.lock
- app/pubspec.yaml
- catalog/pubspec.lock
- core/data/lib/src/quest_repository.dart
- core/data/pubspec.lock
- core/database/lib/isar.dart
- core/database/lib/src/di/isar.dart
- core/database/lib/src/initializer.dart
- core/database/lib/src/quest/isar_quest_dao.dart
- core/database/lib/src/quest/quest_dao.dart
- core/database/pubspec.lock
- core/database/pubspec.yaml
- core/domain/pubspec.lock
- feature/auth/pubspec.lock
- feature/home/pubspec.lock
- feature/quest/pubspec.lock
- feature/settings/pubspec.lock
- melos.yaml
- close #229  🦕
ローカルデータベース関連の操作を正常に動作するよう修正します．
-
> [GH-229] ローカルデータベース関連の操作を正常に動作するよう修正

- core/data/lib/src/quest_repository.dart
- core/database/lib/src/quest/isar_quest_dao.dart
- core/database/lib/src/quest/quest_dao.dart
- core/designsystem/lib/src/component/scaffold/scaffold.dart
- core/domain/lib/quest_use_case.dart
- core/domain/lib/src/use_case/quest/add_quest_use_case.dart
- core/domain/lib/src/use_case/quest/add_quest_use_case.g.dart
- core/domain/lib/src/use_case/quest/quest_list_stream_use_case.dart
- core/domain/lib/src/use_case/quest/quest_list_stream_use_case.g.dart
- core/domain/lib/src/use_case/use_case.dart
- core/domain/lib/use_case.dart
- core/domain/pubspec.lock
- core/domain/pubspec.yaml
- feature/quest/lib/src/ui/quest/quest_page.dart
- close #232 🦕
クエスト一覧をローカルで動作するようにします．
-
> [GH-232] クエスト一覧をローカルで動作するようにする

- catalog/lib/components/scaffold.dart
- core/designsystem/lib/src/component/app_bar/app_bar.dart
- core/designsystem/lib/src/component/app_bar/index.dart
- core/designsystem/lib/src/component/index.dart
- feature/auth/lib/src/ui/auth/auth_page.dart
- feature/home/lib/src/ui/home/home_page.dart
- feature/quest/lib/src/ui/quest/quest_page.dart
- feature/settings/lib/src/ui/settings/settings_page.dart
- close #234 🦕
AsisAppBar を追加し AppBar の使用箇所を置き換えます．
-
> [GH-234] AsisAppBar を追加し AppBar の使用箇所を置き換え

- core/domain/lib/src/use_case/quest/add_quest_use_case.dart
- feature/quest/lib/src/ui/quest/quest_page.dart
- feature/quest/lib/src/ui/quest/quest_page_action.dart
- feature/quest/lib/src/ui/quest/quest_page_state.dart
- feature/quest/lib/src/ui/quest/quest_page_state.freezed.dart
- feature/quest/lib/src/ui/quest/quest_page_state_machine.dart
- feature/quest/lib/src/ui/quest/quest_page_state_machine.g.dart
- feature/quest/pubspec.lock
- feature/quest/pubspec.yaml
- close #238 🦕
クエスト一覧の状態管理をカイゼンします．
-
> [GH-238] クエスト一覧の状態管理をカイゼン

- core/domain/lib/src/use_case/quest/quest_list_stream_use_case.dart
- core/domain/lib/src/use_case/quest/quest_list_stream_use_case.g.dart
- feature/quest/lib/src/ui/quest/quest_page.dart
- feature/quest/lib/src/ui/quest/quest_page_state.dart
- feature/quest/lib/src/ui/quest/quest_page_state.freezed.dart
- feature/quest/lib/src/ui/quest/quest_page_state_machine.dart
- feature/quest/lib/src/ui/quest/quest_page_state_machine.g.dart
- close #243 🦕
QuestListStreamUseCase 自体へのアノテーション付与に変更します．
これにより，Widget 側で Stream ではなく AsyncValue として扱えるようになります．
-
> [GH-243] QuestListStreamUseCase 自体へのアノテーション付与に変更

- app/lib/router/app_page_path.dart
- app/lib/router/go_route/quest_list_route.dart
- app/lib/router/go_route/quest_list_route.g.dart
- app/lib/router/shell_route/app_shell_route.g.dart
- catalog/lib/components/quest_list_tile.dart
- catalog/lib/pages/quest_detail_page.dart
- catalog/lib/pages/quest_page.dart
- catalog/lib/widgetbook.directories.g.dart
- core/ui/lib/src/quest_list_tile.dart
- feature/quest/lib/feature_quest.dart
- feature/quest/lib/src/ui/detail/quest_detail_page.dart
- feature/quest/lib/src/ui/detail/quest_detail_page_action.dart
- feature/quest/lib/src/ui/detail/quest_detail_page_state.dart
- feature/quest/lib/src/ui/detail/quest_detail_page_state.freezed.dart
- feature/quest/lib/src/ui/detail/quest_detail_page_state_machine.dart
- feature/quest/lib/src/ui/detail/quest_detail_page_state_machine.g.dart
- feature/quest/lib/src/ui/detail/quest_detail_route.dart
- feature/quest/lib/src/ui/list/quest_list_page.dart
- feature/quest/lib/src/ui/list/quest_list_route.dart
- close #246 🦕
クエスト詳細画面の簡易実装を追加します．
-
> [GH-246] クエスト詳細画面の簡易実装を追加

- core/data/lib/src/quest_repository.dart
- core/database/lib/src/di/isar.g.dart
- core/database/lib/src/quest/isar_quest_dao.dart
- core/database/lib/src/quest/model/quest.dart
- core/database/lib/src/quest/quest_dao.dart
- core/database/lib/src/quest/quest_dao.g.dart
- core/domain/lib/quest_use_case.dart
- core/domain/lib/src/use_case/quest/quest_stream_by_id_use_case.dart
- core/domain/lib/src/use_case/quest/quest_stream_by_id_use_case.g.dart
- feature/quest/lib/src/ui/detail/quest_detail_page.dart
- feature/quest/lib/src/ui/detail/quest_detail_page_state.dart
- feature/quest/lib/src/ui/detail/quest_detail_page_state.freezed.dart
- feature/quest/lib/src/ui/detail/quest_detail_page_state_machine.dart
- feature/quest/lib/src/ui/detail/quest_detail_page_state_machine.g.dart
- close #252 🦕
クエスト詳細取得のユースケースを追加します．
-
> [GH-252] クエスト詳細取得のユースケースを追加

- app/pubspec.lock
- catalog/pubspec.lock
- core/designsystem/lib/component.dart
- core/designsystem/lib/src/space/space.dart
- core/designsystem/pubspec.lock
- core/designsystem/pubspec.yaml
- core/ui/pubspec.lock
- feature/auth/pubspec.lock
- feature/home/pubspec.lock
- feature/quest/pubspec.lock
- feature/settings/pubspec.lock
- close #272 🦕
Gap パッケージを導入します．
-
> [GH-272] Gap パッケージを導入

- app/ios/Podfile.lock
- app/pubspec.lock
- backend/pubspec.lock
- catalog/pubspec.lock
- core/analytics/pubspec.lock
- core/authenticator/pubspec.lock
- core/common/pubspec.lock
- core/data/pubspec.lock
- core/database/pubspec.lock
- core/datastore/pubspec.lock
- core/designsystem/pubspec.lock
- core/designsystem/pubspec.yaml
- core/domain/pubspec.lock
- core/model/pubspec.lock
- core/network/pubspec.lock
- core/testing/pubspec.lock
- core/ui/pubspec.lock
- feature/auth/pubspec.lock
- feature/home/pubspec.lock
- feature/quest/pubspec.lock
- feature/settings/pubspec.lock
- melos.yaml
- pubspec.lock
間接的に依存しているライブラリのバージョンアップが Renovate で対応できていなかったため，手動で dart pub upgrade します．
- CI が通ること
- https://dart.dev/tools/pub/cmd/pub-upgrade
> chore(deps): 依存ライブラリのバージョンアップ

- melos.yaml
- close #317 🦕
melos 内のバージョン記載を削除します．
-
> [GH-317] melos 内のバージョン記載を削除

- melos.yaml
- close #325 🦕
test の concurrency を 1 に設定します．
- CI が正常終了すること
-
> [GH-325] test の concurrency を 1 に設定

- core/common/lib/collection.dart
- core/common/pubspec.lock
- core/common/pubspec.yaml
- close #323 🦕
common パッケージに collection を追加します．
- https://pub.dev/packages/collection
> [GH-323] common パッケージに collection を追加

- app/android/app/build.gradle
> chore(app): jvm 11 -> 17

- .github/workflows/firebase-hosting-merge.yml
- .github/workflows/firebase-hosting-pull-request.yml
firebase hosting のデプロイ調整を実施します．
-
> ci: firebase hosting のデプロイ調整

- .github/labeler.yml
- .github/labels.yml
- .github/release.yml
- close #374 🦕
type ラベルのカイゼンを実施します．
-
> [GH-374] ci: type ラベルのカイゼン

- .github/labeler.yml
- .github/labels.yml
core/network_ferry のラベルを追加します。
-
> ci(label): core/network_ferry のラベルを追加

- core/analytics/pubspec.lock
- core/analytics/pubspec.yaml
- core/analytics/test/dummy_test.dart
- core/authenticator/pubspec.lock
- core/authenticator/pubspec.yaml
- core/authenticator/test/dummy_test.dart
- core/database/pubspec.lock
- core/database/pubspec.yaml
- core/database/test/dummy_test.dart
- core/datastore/pubspec.lock
- core/datastore/pubspec.yaml
- core/datastore/test/dummy_test.dart
- core/network/pubspec.lock
- core/network/pubspec.yaml
- core/network/test/dummy_test.dart
> test: 不要なテストの削除

- app/backend/pubspec.lock
- app/catalog/pubspec.lock
- app/mobile/pubspec.lock
- core/analytics/pubspec.lock
- core/analytics_firebase/pubspec.lock
- core/authenticator/pubspec.lock
- core/common/pubspec.lock
- core/data/pubspec.lock
- core/database/pubspec.lock
- core/database_isar/pubspec.lock
- core/datastore/pubspec.lock
- core/designsystem/pubspec.lock
- core/domain/pubspec.lock
- core/model/pubspec.lock
- core/network/pubspec.lock
- core/network_model/pubspec.lock
- core/ui/pubspec.lock
- feature/auth/pubspec.lock
- feature/feed/pubspec.lock
- feature/home/pubspec.lock
- feature/quest/pubspec.lock
- feature/settings/pubspec.lock
> fix(deps): 依存ライブラリのバージョンアップ

- core/model/test/quest/quest_count_test.dart
- close #531 🦕
クエスト数モデルのテストコードを追加します。
-
> test(model): クエスト数モデルのテストコードを追加

- app/catalog/pubspec.lock
- app/mobile/pubspec.lock
- feature/auth/pubspec.lock
- feature/home/pubspec.lock
- feature/quest/pubspec.lock
- feature/settings/pubspec.lock
flutter pub upgrade を実施します。
主な目的は video_player_android のバージョンを 2.7.7 にすることで Android のビルドができるようになることのためです。
-
> fix(deps): flutter pub upgrade
